### ISSUE TITLE
Error with BCML

### ISSUE THREAD

**Issue by Lucky2614** [zeldamods/wszst_yaz0#1]
i've tried to install mods just as it says in the bcml page , followed and installed everything but I get a unable to install , and that sort of stuff , the error.log says 

Traceback (most recent call last):

  File "c:\users\n0v4\appdata\local\programs\python\python37\lib\site-packages\bcml\install.py", line 170, in main

    s : sarc.SARC = sarc.read_file_and_make_sarc(pack)

  File "c:\users\n0v4\appdata\local\programs\python\python37\lib\site-packages\sarc\sarc.py", line 433, in read_file_and_make_sarc

    data = wszst_yaz0.decompress(f.read())

  File "c:\users\n0v4\appdata\local\programs\python\python37\lib\site-packages\wszst_yaz0\__init__.py", line 26, in decompress

    stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True).stdout

  File "c:\users\n0v4\appdata\local\programs\python\python37\lib\subprocess.py", line 472, in run

    with Popen(*popenargs, **kwargs) as process:

  File "c:\users\n0v4\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init__

    restore_signals, start_new_session)

  File "c:\users\n0v4\appdata\local\programs\python\python37\lib\subprocess.py", line 1178, in _execute_child

    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by leoetlino** [comment]
Please use the [BotW modding Discord server](https://discordapp.com/invite/2WZF37g) for support questions.
